import test from 'node:test';
import assert from 'node:assert/strict';
import {initial,edit,undo,redo,add,move,textEdit,HISTORY_LIMIT} from '../web/core.mjs';
const doc=()=>({schema_version:1,id:'test',title:'문서',width:800,height:500,elements:[]});
test('add does not mutate original and snapshots are independent',()=>{const d=doc(),s=edit(initial(d),add(d,'text','a'));assert.equal(d.elements.length,0);const next=add(s.present,'rectangle','b');next.elements[1].x=99;assert.equal(s.present.elements.length,1);});
test('undo redo and branching',()=>{let s=initial(doc());s=edit(s,add(s.present,'text','a'));s=edit(s,textEdit(s.present,'a','수정'));s=undo(s);assert.equal(s.present.elements[0].text,'나의 첫 문장');assert.equal(redo(s).present.elements[0].text,'수정');s=edit(s,{...s.present,title:'분기'});assert.equal(s.future.length,0);});
test('movement clamps and ignores invalid numbers',()=>{const d=add(doc(),'rectangle','a');const moved=move(d,'a',1000,-50);assert.equal(moved.elements[0].x,600);assert.equal(moved.elements[0].y,0);assert.equal(move(d,'a',NaN,1),d);});
test('history is bounded and empty history is safe',()=>{let s=initial(doc());assert.equal(undo(s),s);assert.equal(redo(s),s);for(let i=0;i<70;i++)s=edit(s,{...s.present,title:String(i)});assert.equal(s.past.length,HISTORY_LIMIT);});
test('selection is outside document and resets on undo',()=>{let s=initial(doc());s={...edit(s,add(s.present,'text','a')),selection:'a'};assert.equal(s.present.selection,undefined);assert.equal(undo(s).selection,null);});
test('text edits are undoable and bounded',()=>{let s=initial(add(doc(),'text','a'));s=edit(s,textEdit(s.present,'a','가'.repeat(600)));assert.equal(s.present.elements[0].text.length,500);assert.equal(undo(s).present.elements[0].text,'나의 첫 문장');});
