"""외부 채팅 원장. 내부 DM 테이블을 변경하지 않습니다."""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    schema = op.get_context().opts["version_table_schema"]
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column(
            "idempotency_supported", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "lookup_supported", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema=schema,
    )
    op.create_table(
        "external_conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("external_conversation_id", sa.Text(), nullable=False),
        sa.Column("last_seq", sa.BigInteger(), server_default="0", nullable=False),
        sa.CheckConstraint("last_seq >= 0", name="ck_external_conversations_seq"),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            [f"{schema}.external_connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id",
            "external_conversation_id",
            name="uq_external_conversations_provider",
        ),
        sa.UniqueConstraint(
            "id", "connection_id", name="uq_external_conversations_connection"
        ),
        schema=schema,
    )
    op.create_table(
        "external_participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("external_sender_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            [f"{schema}.external_connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id",
            "external_sender_id",
            name="uq_external_participants_provider",
        ),
        sa.UniqueConstraint(
            "id", "connection_id", name="uq_external_participants_connection"
        ),
        schema=schema,
    )
    op.create_table(
        "external_members",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            [f"{schema}.external_conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [f"{schema}.users.id"],
        ),
        sa.PrimaryKeyConstraint("conversation_id", "user_id"),
        schema=schema,
    )
    op.create_table(
        "external_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("participant_id", sa.Uuid(), nullable=True),
        sa.Column("operator_user_id", sa.Uuid(), nullable=True),
        sa.Column("client_message_id", sa.Uuid(), nullable=True),
        sa.Column("external_message_id", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("payload_hash", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(participant_id IS NOT NULL AND operator_user_id IS NULL AND external_message_id IS NOT NULL AND client_message_id IS NULL) OR (participant_id IS NULL AND operator_user_id IS NOT NULL AND external_message_id IS NULL AND client_message_id IS NOT NULL)",
            name="ck_external_messages_sender",
        ),
        sa.CheckConstraint("seq > 0", name="ck_external_messages_seq"),
        sa.ForeignKeyConstraint(
            ["conversation_id", "connection_id"],
            [
                f"{schema}.external_conversations.id",
                f"{schema}.external_conversations.connection_id",
            ],
            name="fk_external_messages_conversation",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id", "operator_user_id"],
            [
                f"{schema}.external_members.conversation_id",
                f"{schema}.external_members.user_id",
            ],
            name="fk_external_messages_operator",
        ),
        sa.ForeignKeyConstraint(
            ["participant_id", "connection_id"],
            [
                f"{schema}.external_participants.id",
                f"{schema}.external_participants.connection_id",
            ],
            name="fk_external_messages_participant",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id",
            "external_message_id",
            name="uq_external_messages_provider",
        ),
        sa.UniqueConstraint(
            "conversation_id",
            "operator_user_id",
            "client_message_id",
            name="uq_external_messages_client",
        ),
        sa.UniqueConstraint("conversation_id", "seq", name="uq_external_messages_seq"),
        sa.UniqueConstraint(
            "id", "connection_id", name="uq_external_messages_connection"
        ),
        schema=schema,
    )
    op.create_table(
        "external_inbound_events",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("payload_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            [f"{schema}.external_connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id", "connection_id"],
            [
                f"{schema}.external_messages.id",
                f"{schema}.external_messages.connection_id",
            ],
            name="fk_external_events_message",
        ),
        sa.PrimaryKeyConstraint("connection_id", "event_id"),
        schema=schema,
    )
    op.create_table(
        "external_outbound_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.Text(), server_default="pending", nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effect_id", sa.Text(), nullable=True),
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'sending' AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL) OR (state <> 'sending' AND lease_token IS NULL AND lease_expires_at IS NULL)",
            name="ck_external_jobs_lease",
        ),
        sa.CheckConstraint(
            "state <> 'accepted' OR effect_id IS NOT NULL",
            name="ck_external_jobs_accepted",
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'sending', 'accepted', 'rejected', 'unknown')",
            name="ck_external_jobs_state",
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_external_jobs_attempts"),
        sa.ForeignKeyConstraint(
            ["message_id"],
            [f"{schema}.external_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
        schema=schema,
    )
    op.create_index(
        "ix_external_jobs_ready",
        "external_outbound_jobs",
        ["state", "next_attempt_at"],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    schema = op.get_context().opts["version_table_schema"]
    for name in (
        "external_outbound_jobs",
        "external_inbound_events",
        "external_messages",
        "external_members",
        "external_participants",
        "external_conversations",
        "external_connections",
    ):
        op.drop_table(name, schema=schema)
