apiVersion: v1
kind: Namespace
metadata:
  name: laughtale-chat-external
  labels:
    app.kubernetes.io/part-of: laughtale-chat-external
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lab-budget
spec:
  hard:
    pods: "9"
    requests.cpu: "700m"
    requests.memory: 1Gi
    limits.cpu: "2500m"
    limits.memory: 2Gi
